version: 0.2 

phases:
  install: 
    runtime-versions:
      java: openjdk8
    commands: 
      - echo Nothing to do the install phase....
  pre_build:
     commands:
      - echo Build started on `date`
      - mvn install 
  post_build: 
    commands: 
      - echo build completed on `date`
artifacts:
  files:
    - 'target/ccdemo-java.war'     
